### ISSUE TITLE
Prevent automatic creation of type class instances

### ISSUE THREAD

**Issue by hannespernpeintner** [arrow-kt/kotlin#12]
This one is two questions out of curiosity more than anything else. I saw that the current implementation finds matching type classes and inserts them into parameters with a constructor call.

1. Obviously this fails when the constructor is made private. Since this doesn't make much sense at all, is there any idea to prevent the user from doing this?
2. Will there be a way to prevent these instantiations in the future? If yes, would the compiler to some caching on his own, or is the plan to allow _extension object_ s for the user, so that instead of providing an extension class, he can provide an object?

**Comment by hannespernpeintner** [comment]
Super nice! I think that provides everything one needs for usage in scenarios with higher Performance demands. Are there any restrictions for extension objects, for example can they only be top level and in companions and so on?

**Comment by truizlop** [comment]
Restrictions are the same as for extension classes; i.e. they are going to be resolved if they are defined in the right places where the compiler is going to search.

**Comment by hannespernpeintner** [comment]
Okay, this is as expected and nice. Thanks for your really outstanding work here.
