### ISSUE TITLE
Explore how to deploy KEEP Kotlin compiler plugin

### ISSUE THREAD

**Issue by truizlop** [arrow-kt/kotlin#19]
Explore ways to deploy the modified Kotlin compiler plugin for the KEEP to bintray / mavencentral / whatever repos that are used from the IDE plugins import settings, so you can easily import it using the IDE without the need to mess with zip files.

The overall goal is to ease the testing process.

**Comment by JorgeCastilloPrz** [comment]
Already done. Provided details in our private repo about how to deploy new versions.
