### ISSUE TITLE
Syntax for `given` parameters

### ISSUE THREAD

**Issue by diesalbla** [arrow-kt/kotlin#2]
The syntax for class and method definitions should be extended to allow a _given_ clause. The _given_ clause would appear between the declared type of the function and the body definition as separated by the `=` sign. The _given_ clause would consist of the `given` keyword, followed by a type expression. 
This type expression could include any type variable (type parameter) in the declaration of the function, or which is the scope that contains the function:

```Kotlin
fun <A> add(a: A, b: A): A  given Monoid<A> =  a
```

The issue should include the following:
* Modify the syntactic definition to support the given clause.
* Modify the documentation of the program syntax.

We leave out of this issue:
* Making the members of the `given` parameter available in the body of the function. 
* Resolution of the `given` parameter.

**Comment by raulraja** [comment]
This has now changed to `with` in the latest version of the proposal and in `varargs` style position:
```kotlin
fun <A> add(a: A, b: A, given Monoid<A>): A  =  a.combine(b)
```
If they are implemented as parameters we can preserve compatibility with Java by allowing java caller to pass in the specific instance. Naming the instance is currently optional based on latest discussions. This is also a valid form:
```kotlin
fun <A> add(a: A, b: A, given MA: Monoid<A>): A  =  with (MA) { a.combine(b) }
```
Naming arguments allows for disambiguation when there are potentially multiple instances of the same extension interface targeting different types in the same scope and they provide colliding functions. 
This is very similar to the way sub typing work in the sense that when we have multiple instances of a type class that all should activate the syntax is the same as if we were creating a sub type of all of them so it provides a common scope without boilerplate of multiple nested `with(a){with(b) {{}}}`.

In a sub typing relationship today Kotlin will fail with a compilation error if you fail to override a method that appears with ambiguity in two unrelated super types.

**Comment by truizlop** [comment]
@raulraja, I have a couple of questions:

1. I have seen in the KEEP thread some examples where some of the instances were provided in the beginning of the parameter list and some other times they appeared at the end. I assume, given your comment above, that they will appear always at the end, in the style of `vararg` parameters. Is this assumption correct?

2. Are we allowing to provide `given` instances only in functions / methods? Could they appear in constructor declarations as well? Could they appear in other situations? I've seen some examples in the thread where people were declaring fields with the `given` keyword and expecting them to be resolved.

**Comment by truizlop** [comment]
Also, are we using `given` or `with` (as in [this example](https://github.com/arrow-kt/kotlin/issues/3#issuecomment-384780189))?

**Comment by raulraja** [comment]
@truizlop `with` replaces `given`

**Comment by raulraja** [comment]
Related to your questions:
1. Whatever makes sense, following the same convention as varargs seems like a good idea since it's an idiom developers already understand.
2. Yes they can appear in constructor declarations since certain instances require of other type instances to be made concrete:
```kotlin
extension class OptionMonoid<A>(with M: Monoid<A>) : Monoid<Option<A>> { ... }
```

**Comment by truizlop** [comment]
Given the current [Kotlin grammar](https://kotlinlang.org/docs/reference/grammar.html), this is an initial proposal to include the `with` keyword, under the following assumptions:

- Typeclass instances are always resolved as function or constructor parameters.
- Typeclass instances appear in the last positions of the argument list, in a `vararg` manner.
- Typeclass instances are always named parameters.

## Current grammar

Analyzing the current Kotlin grammar, the points for modification are:

[primaryConstructor](https://kotlinlang.org/docs/reference/grammar.html#primaryConstructor) (used by `class` and `object`)
```
primaryConstructor
: (modifiers "constructor")? ("(" functionParameter{","} ")")
;
```

[valueParameters](https://kotlinlang.org/docs/reference/grammar.html#valueParameters) (used by `secondaryConstructor` and `function`)
```
valueParameters
: "(" functionParameter{","}? ")"
;
```

## New grammar

**New elements**

functionParameters (notice the 's' at the end): represents a list of regular parameters plus implicit typeclass instances at the end.
```
functionParameters
: functionParameter{","} ( "," instanceParameter{","} )?
: instanceParameter{","}
;
```

instanceParameter: a parameter representing a typeclass instance that will be automatically resolved.
```
instanceParameter
: "with" modifier ("val" | "var")? parameter
;
```

**Modified elements**

valueParameters
```
valueParameters
: "(" functionParameters? ")"
;
```

primaryConstructor
```
primaryConstructor
: ( modifiers "constructor" )? ( "(" functionParameters ")" )
;
```

**Comment by raulraja** [comment]
@truizlop that looks like a great start!

**Comment by truizlop** [comment]
It seems an easier change to the grammar can be done to include `with` and `extension`.

## Grammar changes

[classModifier](https://kotlinlang.org/docs/reference/grammar.html#classModifier): modifiers applicable to a `class` or `interface`
```
classModifier
: "abstract"
: "final"
: "enum"
: "open"
: "annotation"
: "sealed"
: "data"
: "extension"
;
```

[parameterModifier](https://kotlinlang.org/docs/reference/grammar.html#parameterModifier): modifiers applicable to a parameter in a function or constructor.

```
parameterModifier
: "noinline"
: "crossinline"
: "vararg"
: "with"
;
```


## Implications and limitations

- `extension` can only be applicable to `class` or `interface`. I think @raulraja mentioned that it would be nice to allow `val` and `fun` as providers of typeclass instances. Is there an example why those are necessary, which cannot be solved by `class` or `interface` and passing arguments through a constructor?
- `with` can be added to any parameter and in any position, not necessarily in the last section of the parameter list. `vararg` behaves in this way. This entails that, when used in the front places of the parameter list, if the instance is not explicitly passed, the rest of arguments need to be named; e.g.:

```kotlin
fun <A> sum(with MA : Monoid<A>, a : A, b : A) : A { ... }

// Invocation with implicitly resolved Monoid instance
sum(a = 1, b = 2)

// Invocation with explicit Monoid instance
sum(IntMonoid(), 1, 2)
```

I think it is consistent with how `vararg` is used and Kotlin developers are already familiar with this pattern.
- If a function requires more than one implicitly resolved instance, each parameter needs to be annotated with `with`, e.g. (using [this example](https://github.com/arrow-kt/kotlin/issues/3#issuecomment-384780189)):

```kotlin
fun <A> fetchSaveAndLog(with repository: Repository<A>, with log : Log<A>): Unit =
  fetchAll().forEach { it.update().log("saved") } 
```

- All `with` parameters need to be named. The reason behind this is consistency and ease of implementation, although the names are not appearing in the function body in most situations (except for disambiguation cases).

## Result

Including these changes in the Kotlin grammar makes the parser able to recognize and highlight the new keywords, but with no effect in the semantics of the language:

<img width="664" alt="Parser with new syntax" src="https://user-images.githubusercontent.com/2371603/45206318-02131680-b285-11e8-8906-8bd262699638.png">

**Comment by JorgeCastilloPrz** [comment]
Really nice investigation work Tomás. Great job!

**Comment by diesalbla** [comment]
Following a recent announcement by @elizarov in https://github.com/Kotlin/KEEP/pull/87#issuecomment-746042751, it seems that the language developers at JetBrains are moving forward with a slightly different proposal, about having _Multiple receivers on extension functions_.  https://youtrack.jetbrains.com/issue/KT-10468

Since any further development on the present issue will follow on the conclussions from that KT ticket, this issue can be closed.
