### ISSUE TITLE
Kotlin Compiler - Analysis

### ISSUE THREAD

**Issue by diesalbla** [arrow-kt/kotlin#4]
In order to implement extension interfaces in the Kotlin compiler, we need to locate the places at the code involved in the following logic:

* Lexical analysis, to add some keywords. 
* Syntax analysis
* Resolution of extension functions, by type.

**Comment by truizlop** [comment]
From the conversation in kotlinlang Slack, #kontributors channel about where to start:
- How scope structures are built: look into `ClassResolutionScopesSupport`
- How scope structures are used for name resolution: look into `NewResolutionOldInference.runResolution`
- In `testData/diagnostics/resolve` we can find examples of tests similar to the purpose of what we want to achieve.

Also, some set of commits for a similar change in the language that can help us locate which files we need to modify:
- [Add platform/impl keywords](https://github.com/JetBrains/kotlin/commit/6e2ef9b1d2d5834c69ca44567faac77dd5dad476)
- [Serialize and deserialize header modifier for descriptors](https://github.com/JetBrains/kotlin/commit/db1f03958629794b6715663cdc8a743cb1500888)

**Comment by diesalbla** [comment]
The work for this issue was succeeded and overtaken by the development of https://github.com/arrow-kt/arrow-meta, an API for compiler plugins and compiler extensions.
